export const PROJECT_V5_SCHEMA_VERSION = 5 as const

export const MAX_IDENTIFIER_UTF8_BYTES_V5 = 128
export const MAX_NAME_UTF8_BYTES_V5 = 128
export const MAX_SOURCE_FILENAME_UTF8_BYTES_V5 = 255
export const MAX_LOGICAL_URI_UTF8_BYTES_V5 = 2_048
export const MAX_OPC_UA_NODE_IDENTIFIER_UTF8_BYTES_V5 = 1_024
export const MAX_OPC_UA_ENDPOINT_URL_UTF8_BYTES_V5 = 2_048

export const MAX_ROBOT_CONTROLLERS_V5 = 8
export const MAX_ROBOT_INSTANCES_V5 = 8
export const MAX_ROBOT_DEFINITIONS_V5 = 8
export const MIN_ROBOT_JOINTS_V5 = 1
export const MAX_ROBOT_JOINTS_V5 = 16
export const MIN_ROBOT_LINKS_V5 = 2
export const MAX_ROBOT_LINKS_V5 = 17
export const MIN_ROBOT_STEP_SOURCES_V5 = 1
export const MAX_ROBOT_STEP_SOURCES_V5 = 7
export const MAX_SPATIAL_ENTITIES_V5 = 256
export const MAX_IMPORTED_OBJECT_STEP_ASSETS_V5 = 128
export const MAX_SCENE_GROUPS_V5 = 256
export const MAX_MOVING_FRAMES_PER_ENTITY_V5 = 32
export const MAX_PROJECT_FRAMES_V5 = 1_024
export const MAX_LOGICAL_SIGNALS_V5 = 1_024
export const MAX_LOGICAL_SIGNAL_STRING_UTF8_BYTES_V5 = 4_096

export const MAX_JOBS_V5 = 32
export const MAX_JOB_STEPS_PER_JOB_V5 = 256
export const MAX_TOTAL_JOB_STEPS_V5 = 2_048
export const MIN_JOB_SPEED_PERCENT_V5 = 1
export const MAX_JOB_SPEED_PERCENT_V5 = 100
export const MAX_JOB_TIMER_MS_V5 = 2_147_483_647

export const MAX_VISIBLE_SCENE_TRIANGLES_V5 = 1_500_000
export const MAX_REFERENCED_STEP_BYTES_V5 = 256 * 1024 * 1024
export const MAX_OBJECT_STEP_BYTES_V5 = 50 * 1024 * 1024
export const MAX_OBJECT_STEP_TRIANGLES_V5 = 250_000
export const MAX_ROBOT_DEFINITION_STEP_BYTES_V5 = 100 * 1024 * 1024
export const MAX_ROBOT_DEFINITION_TRIANGLES_V5 = 600_000
export const BOX_PRIMITIVE_TRIANGLES_V5 = 12
export const CYLINDER_RADIAL_SEGMENTS_V5 = 32 as const
export const CYLINDER_PRIMITIVE_TRIANGLES_V5 = 128

export const MAX_OPC_UA_ENDPOINTS_V5 = 8
export const MAX_OPC_UA_STRUCTURE_ROOTS_V5 = 128
export const MAX_OPC_UA_STRUCTURE_ROOTS_PER_ENDPOINT_V5 = 64
export const MAX_OPC_UA_EXPANDED_LEAVES_V5 = 1_024
export const MAX_OPC_UA_EXPANDED_LEAVES_PER_ENDPOINT_V5 = 512
export const MAX_OPC_UA_EXPANDED_LEAVES_PER_STRUCTURE_V5 = 32
export const MAX_OPC_UA_STRUCTURE_DEPTH_V5 = 4
export const MAX_OPC_UA_FIXED_ARRAY_ELEMENTS_V5 = 256
export const MAX_OPC_UA_LEAF_UPDATES_PER_SECOND_V5 = 10_240
export const DEFAULT_OPC_UA_PUBLISHING_INTERVAL_MS_V5 = 100
export const MIN_OPC_UA_PUBLISHING_INTERVAL_MS_V5 = 50
export const MAX_OPC_UA_VALUES_PER_CALL_V5 = 128
export const MAX_RUNTIME_BATCH_BYTES_V5 = 256 * 1024

export const MAX_OPC_UA_SERVER_SESSIONS_V5 = 16
export const MAX_ACTIVE_COMMAND_DEDUP_RECORDS_V5 = 4_096
export const MAX_EXTERNAL_COMMAND_EXPIRY_MS_V5 = 60_000
export const TERMINAL_COMMAND_RETENTION_MS_V5 = 5 * 60_000
