import { expect, loadV6Demo, selectV6DemoRobot, test } from './ui-v6-fixtures.js'

test('V6 keeps Scene Explorer selection keyboard-operable and routes right clicks to scene actions instead of camera input', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 768 })
  await loadV6Demo(page)
  const inspectorToggle = page.getByRole('button', { name: /Show Inspector|Hide Inspector/u })
  if (await inspectorToggle.getAttribute('aria-pressed') !== 'true') await inspectorToggle.click()

  const tree = page.getByRole('tree', { name: 'Scene Explorer' })
  const canvasHost = page.getByTestId('v6-canvas-host')
  const robot = await selectV6DemoRobot(page)
  const inspector = page.getByTestId('v6-inspector')
  const inspectorBinding = inspector.getByRole('button', { name: 'Open Binding' })
  await inspectorBinding.click()
  const editor = page.getByRole('dialog', { name: 'OPC UA Binding' })
  await editor.getByRole('button', { name: 'Cancel' }).click()
  await expect(inspectorBinding).toBeFocused()

  await robot.press('Shift+F10')
  const explorerActions = page.getByRole('menu', { name: 'Scene actions' })
  await expect(explorerActions).toHaveAttribute('data-surface', 'explorer')
  await explorerActions.getByRole('menuitem', { name: 'Show/Hide' }).press('Enter')
  await expect(tree.getByRole('button', { name: 'Show NED2' })).toBeVisible()
  await robot.click()
  await expect(robot).toHaveAttribute('aria-selected', 'true')

  await canvasHost.click({ button: 'right' })
  const viewportActions = page.getByRole('menu', { name: 'Scene actions' })
  await expect(viewportActions).toHaveAttribute('data-surface', 'viewport')
  await viewportActions.getByRole('menuitem', { name: 'Show/Hide' }).click()
  await expect(tree.getByRole('button', { name: 'Hide NED2' })).toBeVisible()
  await robot.click()
  await expect(robot).toHaveAttribute('aria-selected', 'true')
})

test('V6 presents finite scene geometry and changes the real camera snapshot when Fit All is requested', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 768 })
  const runtimeErrors: string[] = []
  page.on('console', (message) => {
    if (message.type() === 'error') runtimeErrors.push(message.text())
  })
  page.on('pageerror', (error) => runtimeErrors.push(error.message))
  await loadV6Demo(page)

  const presentation = page.getByTestId('v5-scene-presentation')
  const visibleGeometryCount = async (): Promise<number> => Number((await presentation.textContent() ?? '').match(/^(\d+)/u)?.[1] ?? 0)
  const initialVisibleGeometryCount = await visibleGeometryCount()
  expect(initialVisibleGeometryCount).toBeGreaterThan(0)
  const tree = page.getByRole('tree', { name: 'Scene Explorer' })
  const initialTreeItemCount = await tree.getByRole('treeitem').count()
  const expandObjects = page.getByRole('button', { name: 'Expand Objects' })
  if (await expandObjects.isVisible()) await expandObjects.click()
  await expect(page.getByRole('treeitem', { name: /Part/u })).toBeVisible()
  await page.getByRole('menuitem', { name: 'Model', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Add Box', exact: true }).click()
  await expect.poll(async () => tree.getByRole('treeitem').count()).toBeGreaterThan(initialTreeItemCount)
  await expect.poll(visibleGeometryCount).toBeGreaterThan(0)

  const canvas = page.locator('.v5-scene-canvas')
  await page.getByRole('button', { name: 'Home view' }).click()
  const before = await canvas.getAttribute('data-camera-position')
  await page.getByRole('button', { name: 'Fit all visible geometry' }).click()
  await expect.poll(async () => canvas.getAttribute('data-camera-position')).not.toBe(before)
  expect(runtimeErrors).toEqual([])
})

test('V6 keeps the narrow and compact camera toolbar in one row beside the reserved scene-status lane', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 900 })
  await loadV6Demo(page)

  const shell = page.getByTestId('v6-application-shell')
  const toolbar = page.getByTestId('v6-camera-toolbar')
  const presentation = page.getByTestId('v5-scene-presentation')
  await page.setViewportSize({ width: 959, height: 900 })
  await expect(shell).toHaveAttribute('data-workspace-mode', 'narrow')
  await expect(toolbar).toHaveCSS('flex-wrap', 'nowrap')
  const toolbarBox = await toolbar.boundingBox()
  const presentationBox = await presentation.boundingBox()
  expect(toolbarBox).not.toBeNull()
  expect(presentationBox).not.toBeNull()
  expect((presentationBox?.x ?? 0) + (presentationBox?.width ?? 0)).toBeLessThanOrEqual(toolbarBox?.x ?? 0)

  await page.setViewportSize({ width: 1199, height: 900 })
  await expect(shell).toHaveAttribute('data-workspace-mode', 'compact')
  await expect(toolbar).toHaveCSS('flex-wrap', 'nowrap')
  const compactToolbarBox = await toolbar.boundingBox()
  const compactPresentationBox = await presentation.boundingBox()
  expect(compactToolbarBox).not.toBeNull()
  expect(compactPresentationBox).not.toBeNull()
  expect((compactPresentationBox?.x ?? 0) + (compactPresentationBox?.width ?? 0)).toBeLessThanOrEqual(compactToolbarBox?.x ?? 0)
})
