import { validateOpcUaNodeAddressV1, type OpcUaNodeAddressV1 } from '../project-v5/opcua-node-address.js'
import type { OpcUaEndpointV5 } from '../project-v5/types.js'

export interface OpcUaTestConnectionRequestV1 { readonly type: 'opcua-test-connection-request-v1'; readonly protocolVersion: 1; readonly endpoint: OpcUaEndpointV5 }
export type OpcUaTestConnectionResultV1 =
  | { readonly type: 'opcua-test-connection-result-v1'; readonly protocolVersion: 1; readonly outcome: 'succeeded'; readonly namespaces: readonly string[] }
  | { readonly type: 'opcua-test-connection-result-v1'; readonly protocolVersion: 1; readonly outcome: 'failed'; readonly code: string; readonly message: string }
export interface OpcUaNamespaceIndexRequestV1 { readonly type: 'opcua-namespace-index-request-v1'; readonly protocolVersion: 1; readonly endpointId: string; readonly namespaceUri: string }
export interface OpcUaNamespaceIndexResponseV1 { readonly type: 'opcua-namespace-index-response-v1'; readonly protocolVersion: 1; readonly endpointId: string; readonly namespaceUri: string; readonly namespaceIndex: number }
export interface OpcUaAddressSpaceBrowseRequestV1 { readonly type: 'opcua-address-space-browse-request-v1'; readonly protocolVersion: 1; readonly endpointId: string; readonly parentNodeId: string | null; readonly limit: number; readonly continuationToken: string | null }
export interface OpcUaAddressSpaceBrowseReleaseRequestV1 { readonly type: 'opcua-address-space-browse-release-request-v1'; readonly protocolVersion: 1; readonly continuationToken: string }
export interface OpcUaAddressSpaceBrowseNodeV1 { readonly sessionNodeId: string; readonly browseName: string; readonly displayName: string; readonly nodeClass: string; readonly referenceTypeId: string; readonly typeDefinitionId: string | null; readonly hasChildren: boolean; readonly nodeAddress: OpcUaNodeAddressV1 | null }
export interface OpcUaAddressSpaceBrowseResponseV1 { readonly type: 'opcua-address-space-browse-response-v1'; readonly protocolVersion: 1; readonly endpointId: string; readonly parentNodeId: string; readonly nodes: readonly OpcUaAddressSpaceBrowseNodeV1[]; readonly continuationToken: string | null }

function fail(): never { throw new Error('OPCUA_CONNECTIVITY_PROTOCOL_INVALID') }
const MAX_NAMESPACES = 256; const MAX_NAMESPACE_BYTES = 48 * 1024; const MAX_TEXT_BYTES = 4096
function text(value: unknown): value is string { return typeof value === 'string' && value.length > 0 && new TextEncoder().encode(value).byteLength <= MAX_TEXT_BYTES }
function object(value: unknown): Record<string, unknown> { if (value === null || typeof value !== 'object' || Array.isArray(value)) fail(); return value as Record<string, unknown> }
function keys(value: Record<string, unknown>, expected: readonly string[]): void { const actual = Object.keys(value).sort(); const sorted = [...expected].sort(); if (actual.length !== sorted.length || actual.some((key, index) => key !== sorted[index])) fail() }
function nullableText(value: unknown, maximumBytes = MAX_TEXT_BYTES): string | null { return value === null ? null : typeof value === 'string' && value.length > 0 && new TextEncoder().encode(value).byteLength <= maximumBytes ? value : fail() }
function sessionNodeId(value: unknown): string { const candidate = nullableText(value, 8 * 1024); if (candidate === null || !/^ns=(0|[1-9][0-9]*);[isgb]=.+$/u.test(candidate)) fail(); return candidate }
function continuationToken(value: unknown): string | null { const candidate = nullableText(value, 256); if (candidate !== null && !/^[A-Za-z0-9_-]{1,256}$/u.test(candidate)) fail(); return candidate }
export function validateOpcUaTestConnectionResultV1(value: unknown): OpcUaTestConnectionResultV1 {
  const source = object(value)
  if (source.outcome === 'succeeded') { keys(source, ['type', 'protocolVersion', 'outcome', 'namespaces']); if (source.type !== 'opcua-test-connection-result-v1' || source.protocolVersion !== 1 || !Array.isArray(source.namespaces) || source.namespaces.length > MAX_NAMESPACES || source.namespaces.some((item) => !text(item)) || new Set(source.namespaces).size !== source.namespaces.length || source.namespaces.reduce((total, item) => total + new TextEncoder().encode(item).byteLength, 0) > MAX_NAMESPACE_BYTES) fail(); return Object.freeze({ type: source.type, protocolVersion: 1, outcome: 'succeeded', namespaces: Object.freeze([...source.namespaces]) }) }
  keys(source, ['type', 'protocolVersion', 'outcome', 'code', 'message']); if (source.type !== 'opcua-test-connection-result-v1' || source.protocolVersion !== 1 || source.outcome !== 'failed' || !text(source.code) || !text(source.message)) fail(); return Object.freeze({ type: source.type, protocolVersion: 1, outcome: 'failed', code: source.code, message: source.message })
}
export function validateOpcUaNamespaceIndexResponseV1(value: unknown): OpcUaNamespaceIndexResponseV1 { const source = object(value); keys(source, ['type', 'protocolVersion', 'endpointId', 'namespaceUri', 'namespaceIndex']); const namespaceIndex = source.namespaceIndex; if (source.type !== 'opcua-namespace-index-response-v1' || source.protocolVersion !== 1 || !text(source.endpointId) || !text(source.namespaceUri) || typeof namespaceIndex !== 'number' || !Number.isSafeInteger(namespaceIndex) || namespaceIndex < 0) fail(); return Object.freeze({ type: source.type, protocolVersion: 1, endpointId: source.endpointId, namespaceUri: source.namespaceUri, namespaceIndex }) }
export function validateOpcUaAddressSpaceBrowseRequestV1(value: unknown): OpcUaAddressSpaceBrowseRequestV1 { const source = object(value); keys(source, ['type', 'protocolVersion', 'endpointId', 'parentNodeId', 'limit', 'continuationToken']); const limit = source.limit; if (source.type !== 'opcua-address-space-browse-request-v1' || source.protocolVersion !== 1 || !text(source.endpointId) || typeof limit !== 'number' || !Number.isSafeInteger(limit) || limit < 1 || limit > 100) fail(); const parentNodeId = source.parentNodeId === null ? null : sessionNodeId(source.parentNodeId); const token = continuationToken(source.continuationToken); if (token !== null && parentNodeId === null) fail(); return Object.freeze({ type: source.type, protocolVersion: 1, endpointId: source.endpointId, parentNodeId, limit, continuationToken: token }) }
export function validateOpcUaAddressSpaceBrowseReleaseRequestV1(value: unknown): OpcUaAddressSpaceBrowseReleaseRequestV1 { const source = object(value); keys(source, ['type', 'protocolVersion', 'continuationToken']); const token = continuationToken(source.continuationToken); if (source.type !== 'opcua-address-space-browse-release-request-v1' || source.protocolVersion !== 1 || token === null) fail(); return Object.freeze({ type: source.type, protocolVersion: 1, continuationToken: token }) }
export function validateOpcUaAddressSpaceBrowseResponseV1(value: unknown): OpcUaAddressSpaceBrowseResponseV1 { const source = object(value); keys(source, ['type', 'protocolVersion', 'endpointId', 'parentNodeId', 'nodes', 'continuationToken']); if (source.type !== 'opcua-address-space-browse-response-v1' || source.protocolVersion !== 1 || !text(source.endpointId) || !Array.isArray(source.nodes) || source.nodes.length > 100) fail(); const parentNodeId = sessionNodeId(source.parentNodeId); const token = continuationToken(source.continuationToken); const nodes = source.nodes.map((raw, index) => { const node = object(raw); keys(node, ['sessionNodeId', 'browseName', 'displayName', 'nodeClass', 'referenceTypeId', 'typeDefinitionId', 'hasChildren', 'nodeAddress']); const nodeAddress = node.nodeAddress === null ? null : validateOpcUaNodeAddressV1(node.nodeAddress, `$.nodes[${index}].nodeAddress`); if (!text(node.browseName) || !text(node.displayName) || !text(node.referenceTypeId) || (node.typeDefinitionId !== null && !text(node.typeDefinitionId)) || typeof node.nodeClass !== 'string' || !['Object', 'Variable', 'Method', 'ObjectType', 'VariableType', 'ReferenceType', 'DataType', 'View', 'Unspecified'].includes(node.nodeClass) || typeof node.hasChildren !== 'boolean') fail(); return Object.freeze({ sessionNodeId: sessionNodeId(node.sessionNodeId), browseName: node.browseName, displayName: node.displayName, nodeClass: node.nodeClass, referenceTypeId: node.referenceTypeId, typeDefinitionId: node.typeDefinitionId, hasChildren: node.hasChildren, nodeAddress }) }); return Object.freeze({ type: source.type, protocolVersion: 1, endpointId: source.endpointId, parentNodeId, nodes: Object.freeze(nodes), continuationToken: token }) }
