export const PROJECT_V4_SCHEMA_VERSION = 4 as const

export const MAX_IDENTIFIER_UTF8_BYTES_V4 = 128
export const MAX_NAME_UTF8_BYTES_V4 = 128
export const MAX_SOURCE_FILENAME_UTF8_BYTES_V4 = 255
export const MAX_LOGICAL_URI_UTF8_BYTES_V4 = 2_048
export const MAX_OPCUA_NODE_ID_UTF8_BYTES_V4 = 1_024
export const MAX_OPCUA_ENDPOINT_URL_UTF8_BYTES_V4 = 2_048

export const MAX_ROBOT_INSTANCES_V4 = 8
export const MAX_ROBOT_DEFINITIONS_V4 = 8
export const MIN_ROBOT_JOINTS_V4 = 1
export const MAX_ROBOT_JOINTS_V4 = 16
export const MIN_ROBOT_LINKS_V4 = 2
export const MAX_ROBOT_LINKS_V4 = 17
export const MIN_ROBOT_STEP_SOURCES_V4 = 1
export const MAX_ROBOT_STEP_SOURCES_V4 = 7
export const MAX_SPATIAL_ENTITIES_V4 = 256
export const MAX_IMPORTED_OBJECT_STEP_ASSETS_V4 = 128
export const MAX_SCENE_GROUPS_V4 = 256
export const MAX_MOVING_FRAMES_PER_ENTITY_V4 = 32
export const MAX_PROJECT_FRAMES_V4 = 1_024
export const MAX_ACTION_DEFINITIONS_V4 = 256

export const MAX_JOBS_V4 = 32
export const MAX_JOB_STEPS_PER_JOB_V4 = 256
export const MAX_TOTAL_JOB_STEPS_V4 = 2_048
export const MIN_JOB_SPEED_PERCENT_V4 = 1
export const MAX_JOB_SPEED_PERCENT_V4 = 100

export const MAX_VISIBLE_SCENE_TRIANGLES_V4 = 1_500_000
export const MAX_REFERENCED_STEP_BYTES_V4 = 256 * 1024 * 1024
export const MAX_OBJECT_STEP_BYTES_V4 = 50 * 1024 * 1024
export const MAX_OBJECT_STEP_TRIANGLES_V4 = 250_000
export const MAX_ROBOT_DEFINITION_STEP_BYTES_V4 = 100 * 1024 * 1024
export const MAX_ROBOT_DEFINITION_TRIANGLES_V4 = 600_000
export const BOX_PRIMITIVE_TRIANGLES_V4 = 12
export const CYLINDER_RADIAL_SEGMENTS_V4 = 32 as const
export const CYLINDER_PRIMITIVE_TRIANGLES_V4 = 128

export const MAX_OPCUA_ENDPOINTS_V4 = 8
export const MAX_OPCUA_STRUCTURE_ROOTS_V4 = 128
export const MAX_OPCUA_STRUCTURE_ROOTS_PER_ENDPOINT_V4 = 64
export const MAX_OPCUA_EXPANDED_LEAVES_V4 = 1_024
export const MAX_OPCUA_EXPANDED_LEAVES_PER_ENDPOINT_V4 = 512
export const MAX_OPCUA_EXPANDED_LEAVES_PER_STRUCTURE_V4 = 32
export const MAX_OPCUA_STRUCTURE_DEPTH_V4 = 4
export const MAX_OPCUA_FIXED_ARRAY_ELEMENTS_V4 = 256
export const MAX_OPCUA_LEAF_UPDATES_PER_SECOND_V4 = 10_240
export const DEFAULT_OPCUA_PUBLISHING_INTERVAL_MS_V4 = 100
export const MIN_OPCUA_PUBLISHING_INTERVAL_MS_V4 = 50
export const MAX_OPCUA_VALUES_PER_CALL_V4 = 128
export const MAX_RUNTIME_BATCH_BYTES_V4 = 256 * 1024

export const MAX_OPCUA_SERVER_SESSIONS_V4 = 16
export const MAX_ACTIVE_COMMAND_DEDUP_RECORDS_V4 = 4_096
export const MAX_EXTERNAL_COMMAND_EXPIRY_MS_V4 = 60_000
export const TERMINAL_COMMAND_RETENTION_MS_V4 = 5 * 60_000
